### ISSUE TITLE
Broken links in workshop tab

### ISSUE THREAD

**Issue by jeannettetang** [paleocore/paleocore#104]
Honolulu 2013 tab
download zip file with all presentations (39 MB): http://paleocore-qa.tacc.utexas.edu/media/uploads/files/SAA2013_presentations.zip

Austin 2013 tab
Archaeology: http://paleocore.org/ontology/16/
Biology: http://paleocore.org/ontology/17/
Location: http://paleocore.org/ontology/4/
Geological Context: http://paleocore.org/ontology/5/
original document in vue format: http://paleocore-qa.tacc.utexas.edu/media/uploads/files/PaleoCore.vue
You may also download the original cmap file: http://paleocore-qa.tacc.utexas.edu/media/uploads/files/Paleoarchaeology_Term_map.cmap
cmap: http://ftp.ihmc.us/

**Comment by dennereed** [comment]
Fixed.
