### ISSUE TITLE
Streamline Admin views for Terms Mapping

### ISSUE THREAD

**Issue by urban011** [paleocore/paleocore#120]
Currently the admin views for terms are very confusing, because the in-lines do not clearly show which terms belong to which projects. Need to create this visibility without killing performance. Without caching, Django wants to make a separate query for every term drop-down which makes it unusable and highly inefficient.

**Comment by dennereed** [comment]
Admin view updated. Added project inline for each term and pruned terms from DB. Closing this issue.
