### ISSUE TITLE
Database constraint on ProjectTerm model prohibits entering terms

### ISSUE THREAD

**Issue by dennereed** [paleocore/paleocore#122]
I think we have a constraint in place on the ProjectTerm model that requires the combination of term and native to be unique. Good for insuring only one native instance of a given term, but creates a problem if term is reused in multiple projects because the combination term and native=False we expect to occur often. It’s preventing me from associating terms with other projects and from defining the PaleoCore terms.  

What we want is something that tests that for every term there is only one native=True.

For now I think it best to remove the constraint and find another solution. 

Example:

project=drp, term=type, native=False
project=Dublin Core, term=type, native=True
project=Darwin Core, term=type, native=False # Violates constraint b/c drp already has term=type and native=False

![screen shot 2015-07-29 at 10 49 42 am](https://cloud.githubusercontent.com/assets/6537616/8962473/5f2dc632-35e0-11e5-8823-65c003cfee17.png)

**Comment by urban011** [comment]
The DB constraint is not generated from Django code it is created outside. However, you may recall that one of the catalysts for moving to Django 1.8 was a new mechanism to encode more advanced DB features such as this (so called partial index) so once the upgrade to 1.8 is complete I expect to move the partial index into Django code.

We should be able to change the unique_together to project, term and leave the native stuff to the DB for now until we can get it into Django code.

**Comment by urban011** [comment]
Fixed on production.
