### ISSUE TITLE
enable logging, or create an "actions" table?

### ISSUE THREAD

**Issue by wabarr** [paleocore/paleocore#15]
Should we enable detailed logging (which django has the capability to do) and/or create an "actions" table that records the following whenever a database transaction occurs?

```
User       DateTime            Action     Record
wabarr    05/06/14 15:46       delete     drp_occurrence.id = 999
```

**Comment by dennereed** [comment]
Actions performed through the admin pages are logged in table django_admin_log. Actions performed in the shell are not logged, but date_last_modified does record the last touch. These logs suffice for now.
