### ISSUE TITLE
Mammal as family = Life as taxon

### ISSUE THREAD

**Issue by cjcampi** [paleocore/paleocore#166]
Noted via csv export. 
If "verbatim_taxon" (incorrectly) has family level as "Mammal", then "taxon" is listed as "Life", not "Mammalia", although "Mammal" is listed as "Sci Name".

Presumably dropping "Mammal" from "uAnimalia, uChordata, uMammalia, uMammal" would fix "Life" issue, but not sure if this will conflict with "Sci Name" then.

**Comment by dennereed** [comment]
I'll try to improve the script I wrote to automatically assign taxa from scientific name. The script is conservative and thesese cases did not get assigned because the parent taxon isn't appropriate.

**Comment by dennereed** [comment]
Fixed all entries where there was a scientific name but no corresponding taxon. In the process updated all scientific name entries of Mammal to Mammalia, and Hippopotomidae to Hippopotamidae, and Primate to Priamtes.  There are 4 remaining Chelonia specimens but not sure what taxon to assign.
