### ISSUE TITLE
enter schema terms for existing projects

### ISSUE THREAD

**Issue by wabarr** [paleocore/paleocore#17]
only for projects which currently have data

* DRP
* MLP
* Turkana
* Omo

**Comment by dennereed** [comment]
This issue requires also updating the admin for the terms tables. Minimum need to add search function for terms. Perhaps separate admin for Standards vs other projects.

**Comment by dennereed** [comment]
Made updates to terms admin and projects admin so it is much easier to enter and manage terms. Need to push these changes up before we can edit the terms data on production.  PRIORITY.

**Comment by dennereed** [comment]
Updated all terms for Dublin Core. Updated many terms for Darwin Core. Associated terms for PaleoCore. Need now to create public view of PaleoCore terms.
