### ISSUE TITLE
Managing scientific names between tables

### ISSUE THREAD

**Issue by dennereed** [paleocore/paleocore#32]
Scientific names for biology instances are stored in multiple places across at least two tables; the occurrence table has scientificName and then there are several fields in the biology table dedicated to storing names for different parts of the taxonomic hierarchy.  With this comes the risk that the two (or more) areas don't match. We need some sort of automated approach to tracking taxonomic assignments for occurrence instances.

**Comment by urban011** [comment]
Done, moved to production.
