### ISSUE TITLE
Allow GIS direct connections to drp database at TACC

### ISSUE THREAD

**Issue by dennereed** [paleocore/paleocore#41]
A consequence of moving the data from Carmen to TACC is that we simplify the database system, everything is now in one database and we don't need separate database routers in django. The downside is that we break the GIS connections setup for carmen. We need to allow direct access to the database at least for the GIS workstation in SAC 5.186.   WFS is not very reliable. It currently is not working on QGIS from SAC 5.186. Also to make WFS connections in ArcGIS we need the ESRI Data Interoperability extension (ugh!).

**Comment by urban011** [comment]
This is working, both the direct PostGIS connection as well as the WMS and WFS services.

I suspect the issue is that the connection coordinates and logins for one or both services is off since the change. We just need to make sure that those have been updated. The WMS/WFS services should be stable now that they have been moved to the production box.

**Comment by urban011** [comment]
I've documented the connection methods on the blog: http://reedlab.blogspot.com/2015/02/postgis-wms-and-wfs-connections.html

Password and even username information should be kept separately.

**Comment by urban011** [comment]
Sending to Denne to decide how to handle access control.

PostGIS: Only users who absolutely need direct access, ideally this should be zero users!
WFS: Authenticated access. Occurences only, should we provide a shared login or individual logins?
WMS: Publicly accessible right now. Should this be locked down?

**Comment by dennereed** [comment]
Tomislav, Let's close down all WMS access for now. We know it works and how to set it up. That was the earlier goal. Let's keep read only, password access via WFS for Occurrence data from MLP and DRP. Once we do this we can close this issue.

**Comment by dennereed** [comment]
OK this is working for now. Closing issue.
