### ISSUE TITLE
Home not redirecting

### ISSUE THREAD

**Issue by AndCook** [paleocore/paleocore#48]
http://www.paleocore.org/home/ Does not redirect to http://www.paleocore.org as it should. Instead, it just displays a blank page.

Personally, I recommend taking out /home/ from the urls entirely. Is there a purpose for the /home/ link?

**Comment by dennereed** [comment]
The bigger issue is that fiber is returning pages for any unmatched url.

**Comment by urban011** [comment]
OK, the 404 and 500 templates were pointing to the incorrect content block name. Fixed.
