### ISSUE TITLE
Fix search in MLP

### ISSUE THREAD

**Issue by dennereed** [paleocore/paleocore#54]
Searching in MLP and DRP biology raises FieldError.
Cannot resolve keyword 'lowest_level_identification' into field. 

Verify the same issue is not present in DRP.

**Comment by dennereed** [comment]
The issue is restricted to MLP only. It's present in QA and Production.

**Comment by urban011** [comment]
Had a left over reference to lowest_level_identification field in mlp/admin.py, replaced with taxon__name in the search fields list.
