### ISSUE TITLE
Paleosites prefix not used in table names

### ISSUE THREAD

**Issue by urban011** [paleocore/paleocore#59]
For some reason, the paleosites app tables have not been prefixed with the app name. So that we now have a table called "dates" which is not ideal.

**Comment by dennereed** [comment]
Same with the "site" table, also not ideal. I see that the table names are fixed in the Meta classes for these models in paleosites.models.py

**Comment by urban011** [comment]
DB Changes:

ALTER TABLE dates RENAME TO paleosite_date;
ALTER TABLE sites RENAME TO paleosite_site;

**Comment by urban011** [comment]
Done, committed to git.
