### ISSUE TITLE
Redesign Data list view with map

### ISSUE THREAD

**Issue by dennereed** [paleocore/paleocore#61]
Redesign the view at http://paleocore.org/data/
Create a new list view layout showing a map of all paleoanthropology research projects with a button to filter paleocore projects. Under the map include a list of paleocore hosted projects, with link to detail view for each project. Include project name, # of records, whether public or not.

**Comment by wabarr** [comment]
will need an app to track projects within paleocore.  Or maybe the schema or terms app has this information?

**Comment by dennereed** [comment]
Ah, yes. The standard app has a projects table that lists all the paleocore hosted projects. Just need to make that a spatial table.

**Comment by dennereed** [comment]
Actually a problem with using the standard.projects is that the table includes Dublin Core and Darwin Core etc. It's meant to track the projects that have standards and data schemas.

**Comment by wabarr** [comment]
yeah...I will make a paleocore_projects app.  It will track: 

   *  full_name = models.CharField(max_length=300)
   *  abstract = models.TextField(max_length=2000, null=True, blank=True, help_text="A  description of the project, its importance, etc.")
   *   attribution = models.TextField(max_length = 1000, null=True, blank=True, help_text="A description of the people / institutions responsible for collecting the data.")
   *   paleocore_appname = models.CharField(max_length = 200, choices = app_CHOICES)
    *  graphic = models.FileField(max_length=255, null=True, blank=True, upload_to="uploads/images/paleocore_projects")
   *   occurrence_table_name = models.CharField(max_length=255, help_text="the name of the main occurrence table in the models.py file of the associated app")
   *   isPublic = models.BooleanField(default=False, help_text="Is the raw data to be made publicly viewable?")
   *   displaySummaryInfo = models.BooleanField(default=True, help_text="Should project summary data be published? Only uncheck this in extreme circumstances")
    *  geom = models.PointField(srid=4326,db_column="shape")
   *   objects = models.GeoManager()

**Comment by wabarr** [comment]
@dennereed I am making significant progress on this (as well as related issue #62  for new project detail views) This involves creating a new app called paleocore_projects. For maps I use leaflet.js and geodjango, so the new project adds three new installed apps.

*  'paleocore_projects'
*  'leaflet'
*  'djgeojson'

I am also tackling the related issue #18 , but it is proving to be a little more complicated than I thought.

This app will also include the functionality of exposing an interactive data table similar to the django admin for each publicly facing site in the paleocore_projects app.  I creates [issue #67](https://github.com/paleocore/paleocore/issues/67) to track this process

**Comment by wabarr** [comment]
Working prototype up on paleocore_projects branch.  needs optimizing, but proof of principle is there.

**Comment by dennereed** [comment]
What is the correct python package for leaflet? 
django-leaflet == 0.15.2 by Leplatre?

On February 17, 2015 at 7:14:12 AM, Andrew (notifications@github.com) wrote:

@dennereed I am making significant progress on this (as well as related issue #62 for new project detail views) This involves creating a new app called paleocore_projects. For maps I use leaflet.js and geodjango, so the new project adds three new installed apps.

'paleocore_projects'
'leaflet'
'djgeojson'
I am also tackling the related issue #18 , but it is proving to be a little more complicated than I thought.

This app will also include the functionality of exposing an interactive data table similar to the django admin for each publicly facing site in the paleocore_projects app. I creates issue #67 to track this process

**Comment by dennereed** [comment]
Don’t see a package called djgeojson. Is it django-geojson == 2.6.0 by Leplatre?

On February 17, 2015 at 7:14:12 AM, Andrew (notifications@github.com) wrote:

@dennereed I am making significant progress on this (as well as related issue #62 for new project detail views) This involves creating a new app called paleocore_projects. For maps I use leaflet.js and geodjango, so the new project adds three new installed apps.

'paleocore_projects'
'leaflet'
'djgeojson'
I am also tackling the related issue #18 , but it is proving to be a little more complicated than I thought.

This app will also include the functionality of exposing an interactive data table similar to the django admin for each publicly facing site in the paleocore_projects app. I creates issue #67 to track this process

**Comment by wabarr** [comment]
This functionality is up on production
