### ISSUE TITLE
Move DB name and port to secrets

### ISSUE THREAD

**Issue by urban011** [paleocore/paleocore#66]
Currently we have some DB parameters in secrets and some out. This makes it awkward to migrate to QA and Production. Moving all parameters to secrets.

Developers will need to add two new parameters to secrets.py:

(Note: database name should match the individual developer's name for their local instance.)

DATABASE_NAME = 'paleocore_dev'
DATABASE_PORT = '5432'

**Comment by urban011** [comment]
Change committed to Git

**Comment by urban011** [comment]
Moved to QA.

**Comment by urban011** [comment]
There are additional settings that need to be handled on a per environment (i.e. Dev, QA, Prod) basis. I'm going to add the allowed_hosts setting to the secrets.py file so that dev can contain "localhost", QA can contain "paleocore-qa.tacc.utexas.edu", and production can contain ".paleocore.org"

Again, this will require each developer to add an entry into their own dev copy of secrets.py:

ALLOWED_HOSTS = '127.0.0.1'

Also, I've renamed the database properties that were labeled "DEFAULT_*" before, which doesn't make sense anymore to "DATABASE_*"

**Comment by urban011** [comment]
One more host-specific setting: DEBUG_MODE

DEBUG_MODE = True

For Development. Production will of course be False, and QA will be false by default but may need occasional manual switching.

**Comment by urban011** [comment]
Ack! One more setting:

TEMPLATE_DEBUG_MODE = True

**Comment by wabarr** [comment]
@urban011 the latest settings.py from github does not look to secrets.py for those last two settings you mentioned (DEBUG_MODE and TEMPLATE_DEBUG_MODE)

**Comment by urban011** [comment]
Oops! Forgot to check in those changes, should be there now.
