### ISSUE TITLE
dumpdata on production DB produces validation errors

### ISSUE THREAD

**Issue by dennereed** [paleocore/paleocore#69]
I'm trying to get a clean fixture for the entire Paleocore DB off the production server. Running 
python manage.py dumpdata --indent=4 -e sessions -e admin -e contenttypes -e auth.Permissions > ~/paleocore_150220.json

produces the following errors and no data is written to the fixture.

CommandError: One or more models did not validate:
drp.drp_biology: 'taxon' has a relation with model <class 'taxonomy.models.Taxon'>, which has either not been installed or is abstract.
drp.drp_biology: 'identification_qualifier' has a relation with model <class 'taxonomy.models.IdentificationQualifier'>, which has either not been installed or is abstract.
mlp.mlp_biology: 'taxon' has a relation with model <class 'taxonomy.models.Taxon'>, which has either not been installed or is abstract.
mlp.mlp_biology: 'identification_qualifier' has a relation with model <class 'taxonomy.models.IdentificationQualifier'>, which has either not been installed or is abstract.

**Comment by urban011** [comment]
This is now working. However, it does not like "auth.Permissions", it's looking for just "auth" as an app exclusion name.
