### ISSUE TITLE
Create empty sample DB and App for San Francisco conference

### ISSUE THREAD

**Issue by urban011** [paleocore/paleocore#74]
Created in dev. Checked in to github.

**Comment by urban011** [comment]
Created in dev

**Comment by dennereed** [comment]
Looks good in dev. Let's push to QA.  I created a fixture for the test data. I'll upload that to Box.

**Comment by dennereed** [comment]
Tomislav, the san_francisco app has been updated and is ready to push to QA. The data for the app is in a fixture on Box.

**Comment by dennereed** [comment]
Updated unit tests for san francisco app. Closing issue.
